
GenerateArguments:
  model_path: signllava/checkpoints/llama3_8b_pre/
  model_base: meta-llama/Meta-Llama-3-8B-Instruct
  conv_mode: llava_sign_llama_3
  top_p: None
  temperature: 0
  num_beams: 5
  max_new_tokens: 512
  seed: 42
  bf16: True
LoraArguments:
  double_quant: True # Compress the quantization statistics through double quantization.
  quant_type: nf4
  bits: 16 # 4, 8 to enable quantization
  lora_enable: False
  lora_r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  lora_weight_path: ""
  lora_bias: "none"
SignDataArguments:
  context_window_size: 0 #number of preceding sentences
  prelude_window_size: 0 #number of sentences at the beginning of the discourse 
  data_dir: /export/fs06/xzhan138/Sign_LLaVA/mock_data_multi/
  annotation_path:
    test: annotation.dev.json
  visual_features:
    sign2vec:
      enable_input: False
      test: sign2vec/metadata_sign2vec.dev.json
    mae:
      enable_input: False
      test: mae/metadata_mae.dev.json
    dino:
      enable_input: False
      test: dino/metadata_dino.dev.json
    pose:
      enable_input: True
      test: pose/metadata_pose.dev.json
SignModelArguments:
  projectors:
    sign2vec: 
      dim: 768
      projector_type: mlp2x_gelu
    mae: 
      dim: 768
      projector_type: mlp2x_gelu
    dino: 
      dim: 384
      projector_type: mlp2x_gelu
    pose: 
      dim: 32
      projector_type: mlp2x_gelu