
GenerateArguments:
  #model_path: signllava/checkpoints/how2sign_llama3_8b_nocontext_pose_pretrain/
  model_path: signllava/checkpoints/llama3_8b_pre_400ep_mae_dino_sign2vec
  checkpoint_num: 3950
  model_base: meta-llama/Meta-Llama-3-8B-Instruct
  conv_mode: llava_sign_llama_3
  top_p: 1
  min_length: 10
  temperature: 0.1
  do_sample: True # otherwise use greedy decoding
  num_beams: 1
  max_new_tokens: 512
  seed: 42
  bf16: True
LoraArguments:
  double_quant: True # Compress the quantization statistics through double quantization.
  quant_type: nf4
  bits: 16 # 4, 8 to enable quantization
  lora_enable: False
  lora_r: 64
  lora_alpha: 16
  lora_dropout: 0.05
  lora_weight_path: ""
  lora_bias: "none"
SignDataArguments:
  use_paraphrases: False
  context_window_size: 0 #number of preceding sentences
  prelude_window_size: 0 #number of sentences at the beginning of the discourse 
  data_dir: /export/fs06/xzhan138/Sign_LLaVA/signllava/data/How2Sign/
  annotation_path:
    test: annotation.test.json
  visual_features:
    sign2vec:
      enable_input: True
      test: sign2vec/metadata_sign2vec.test.json
    mae:
      enable_input: True
      test: mae/metadata_mae.test.json
    dino:
      enable_input: True
      test: dino/H2S.dino.test.json
    pose:
      enable_input: False
      test: tomas/keypoints/H2S.keypoints.train.json
      #test: pose/metadata_pose.dev.json
SignModelArguments:
  projectors:
    sign2vec: 
      dim: 768
      projector_type: mlp2x_gelu
    mae: 
      dim: 768
      projector_type: mlp2x_gelu
    dino: 
      dim: 1152
      projector_type: mlp2x_gelu
    pose: 
      dim: 208
      projector_type: mlp2x_gelu